/**
 * Exports every row of the live corpus into `supabase/seed.sql`.
 *
 * Run it against the project that currently holds the data:
 *   SUPABASE_URL=... SUPABASE_PUBLISHABLE_KEY=... bun run scripts/export-corpus.ts
 *
 * Then, in the Supabase project you own, run `supabase/schema.sql` followed by
 * `supabase/seed.sql`. Only public reference data is exported (FDA labels,
 * their embedded chunks and the curated Kenya register) — no secrets, no users.
 */
import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const url = process.env["SUPABASE_URL"] ?? process.env["VITE_SUPABASE_URL"];
const key =
  process.env["SUPABASE_PUBLISHABLE_KEY"] ?? process.env["VITE_SUPABASE_PUBLISHABLE_KEY"];

if (!url || !key) {
  console.error("Set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY first.");
  process.exit(1);
}

const supabase = createClient(url, key, {
  auth: { persistSession: false, autoRefreshToken: false },
});

function lit(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (Array.isArray(value)) {
    // text[] / vector both round-trip fine through a quoted literal cast below.
    return `'${JSON.stringify(value).replace(/^\[/, "{").replace(/\]$/, "}").replace(/'/g, "''")}'`;
  }
  if (typeof value === "object") return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

function vectorLit(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  const arr = typeof value === "string" ? value : JSON.stringify(value);
  return `'${arr.replace(/'/g, "''")}'::vector`;
}

async function fetchAll(table: string) {
  const rows: Record<string, unknown>[] = [];
  const pageSize = 500;
  for (let from = 0; ; from += pageSize) {
    const { data, error } = await supabase.from(table).select("*").range(from, from + pageSize - 1);
    if (error) throw error;
    rows.push(...(data ?? []));
    if (!data || data.length < pageSize) break;
  }
  return rows;
}

function statements(table: string, rows: Record<string, unknown>[]) {
  return rows.map((row) => {
    const cols = Object.keys(row).filter((c) => c !== "search_tsv");
    const vals = cols.map((c) => (c === "embedding" ? vectorLit(row[c]) : lit(row[c])));
    return `INSERT INTO public.${table} (${cols.join(", ")}) VALUES (${vals.join(", ")}) ON CONFLICT (id) DO NOTHING;`;
  });
}

const [labels, chunks, kenya] = await Promise.all([
  fetchAll("drug_labels"),
  fetchAll("label_chunks"),
  fetchAll("ke_products"),
]);

const sql = [
  "-- Drug Info Center — corpus seed",
  "-- Generated by scripts/export-corpus.ts. Run AFTER supabase/schema.sql.",
  `-- ${labels.length} labels · ${chunks.length} chunks · ${kenya.length} Kenya products`,
  "",
  "BEGIN;",
  "",
  "-- ------------------------------------------------------------ labels ---",
  ...statements("drug_labels", labels),
  "",
  "-- ------------------------------------------------ embedded passages ---",
  ...statements("label_chunks", chunks),
  "",
  "-- ------------------------------------------- Kenya product register ---",
  ...statements("ke_products", kenya),
  "",
  "COMMIT;",
  "",
].join("\n");

writeFileSync("supabase/seed.sql", sql);
console.log(
  `Wrote supabase/seed.sql — ${labels.length} labels, ${chunks.length} chunks, ${kenya.length} Kenya products.`,
);
