/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskRouteImport } from './routes/ask'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as KenyaRouteImport } from './routes/kenya'
import { Route as DrugsIdRouteImport } from './routes/drugs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const KenyaRoute = KenyaRouteImport.update({
  id: '/kenya',
  path: '/kenya',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugsIdRoute = DrugsIdRouteImport.update({
  id: '/drugs/$id',
  path: '/drugs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/evals': typeof EvalsRoute
  '/interactions': typeof InteractionsRoute
  '/kenya': typeof KenyaRoute
  '/drugs/$id': typeof DrugsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/evals': typeof EvalsRoute
  '/interactions': typeof InteractionsRoute
  '/kenya': typeof KenyaRoute
  '/drugs/$id': typeof DrugsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/evals': typeof EvalsRoute
  '/interactions': typeof InteractionsRoute
  '/kenya': typeof KenyaRoute
  '/drugs/$id': typeof DrugsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/evals'
    | '/interactions'
    | '/kenya'
    | '/drugs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/evals'
    | '/interactions'
    | '/kenya'
    | '/drugs/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/evals'
    | '/interactions'
    | '/kenya'
    | '/drugs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  EvalsRoute: typeof EvalsRoute
  InteractionsRoute: typeof InteractionsRoute
  KenyaRoute: typeof KenyaRoute
  DrugsIdRoute: typeof DrugsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenya': {
      id: '/kenya'
      path: '/kenya'
      fullPath: '/kenya'
      preLoaderRoute: typeof KenyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugs/$id': {
      id: '/drugs/$id'
      path: '/drugs/$id'
      fullPath: '/drugs/$id'
      preLoaderRoute: typeof DrugsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  EvalsRoute: EvalsRoute,
  InteractionsRoute: InteractionsRoute,
  KenyaRoute: KenyaRoute,
  DrugsIdRoute: DrugsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
